title = "xdb - software development"
baseURL = "https://www.xdbsoft.com"
tags = ["portfolio", "web design", "blog"]
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = ""
disqusShortname = "xdbsoft"
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies
publishDir = "docs"

[Params]
    tagline = "software development"
    author = "Simon HEGE"
    description = "Software engineer based in Grasse, France."
    logoBig = "/images/logo-xdb-128.png"
    logoSmall = "/images/logo-xdb-128.png"
    favicon = "favicon.ico"
    opengraphImage = "/images/icon-x-128.png"
    twitter = "simonhege"
    linkedin = "simonhege"
    github = "xdbsoft"
    email = "simon@xdbsoft.com"
    googleTagManager = ""
    highlightJS = true
    copyright = true
    credit = true
    customCSS = false
    cacheBustCSS = false
    cacheBustJS = false
    ajaxFormspree = true

[[menu.main]]
    name = "About"
    url  = "/#about"
    weight = 1
[[menu.main]]
    name = "Blog"
    url  = "/#blog"
    weight = 2
[[menu.main]]
    name = "Contact"
    url  = "/#contact"
    weight = 3